#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > "/dev/null" 2>&1 && pwd )"

source "${SCRIPT_DIR}/../../../setup/environment"

source "${SCRIPT_DIR}/../environment"

Ozone "${SCRIPT_DIR}/ozone.jdebug" &

disown -a
