#!/bin/bash

set -eux -o pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > "/dev/null" 2>&1 && pwd )"

# Later: Use the 'nrfjprog --recover' option if we ever enable 'read-back protection'

NRFJPROG="${HOME}/Developer/Nordic/Tools/Default/nrfjprog/nrfjprog"

"${SCRIPT_DIR}/power" on

"${NRFJPROG}" --eraseall --snr 260114307 # Sensor
#|"${NRFJPROG}" --eraseall --snr 260111065 # Station # TODO Erase, then program the 'uicr.hex' file!

"${SCRIPT_DIR}/power" off perm

# Done
