#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > "/dev/null" 2>&1 && pwd )"

source "${SCRIPT_DIR}/../../setup/environment"

source "${SCRIPT_DIR}/../debug/environment"

set -eux -o pipefail

# Later: Use the 'nrfjprog --recover' option if we ever enable 'read-back protection'

"${SCRIPT_DIR}/power" on

nrfjprog --eraseall --snr "${MIDAIR_SENSOR_JLINK_SN}"
nrfjprog --eraseall --snr "${MIDAIR_STATION_JLINK_SN}"

"${SCRIPT_DIR}/power" off perm

# Done
