#!/bin/bash


SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > "/dev/null" 2>&1 && pwd )"

source "${SCRIPT_DIR}/../../setup/environment"

source "${SCRIPT_DIR}/../debug/environment"

set -eu -o pipefail

if (( $# < 1 )) ; then
    echo "error: required argument(s) are missing"
    exit 1
fi

case "${*}" in

    "on"|"off"|"on perm"|"off perm")
        echo -ne "power ${*}\nq\n" | JLinkExe -SelectEmuBySN "${MIDAIR_SENSOR_JLINK_SN}"  > "/dev/null"
        echo -ne "power ${*}\nq\n" | JLinkExe -SelectEmuBySN "${MIDAIR_STATION_JLINK_SN}" > "/dev/null"
    ;;

    *)
        echo "error: argument(s) must be 'on', 'off', 'on perm', or 'off perm'"
        exit 1
    ;;

esac

echo -ne "q\n" | JLinkExe -SelectEmuBySN "${MIDAIR_SENSOR_JLINK_SN}"
echo -ne "q\n" | JLinkExe -SelectEmuBySN "${MIDAIR_STATION_JLINK_SN}"

# Done
