#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" > "/dev/null" 2>&1 && pwd )"

source "${SCRIPT_DIR}/../../setup/environment"

set -eux -o pipefail

# Later: Use the 'nrfjprog --recover' option if we ever enable 'read-back protection'

"${SCRIPT_DIR}/power" on

nrfjprog --eraseall --snr 260114307 # sensor
nrfjprog --eraseall --snr 260111065 # station

"${SCRIPT_DIR}/power" off perm

# Done
